# Generated by Django 5.1.6 on 2026-02-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tickets', '0002_ticket_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tickets/attachments/%Y/%m/%d/', verbose_name='anexo'),
        ),
    ]
