# Generated by Django 5.1.6 on 2026-02-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tickets', '0003_ticket_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('GITHUB_REPO', 'Novo Repositório no GitHub'), ('GITHUB_USER', 'Adicionar usuário em um repositório no GitHub'), ('SERVICE_OUTAGE', 'Reporte de Indisponibilidade de Serviço'), ('S3_BUCKET', 'Criação de Bucket S3 para um projeto'), ('OTHER', 'Outros')], default='OTHER', max_length=20, verbose_name='categoria'),
        ),
    ]
