# Generated by Django 5.1.6 on 2026-02-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Cliente'), ('ADMIN', 'Administrador'), ('DEVELOPER', 'Desenvolvedor'), ('MANAGER', 'Gerente')], default='CUSTOMER', max_length=10, verbose_name='perfil'),
        ),
    ]
